### ISSUE TITLE
readme图片失效了，不太清楚怎么操作，可以麻烦再补充一下么？

### ISSUE THREAD

**Issue by HAIYAA** [Archie-King/pdf-bookmark#2]

**Comment by Archie-King** [comment]
不好意思，很抱歉没能及时注意到并回复您的邮件。
不知您的问题是否解决？我这边看readme的图片是正常的，可能是您的网络连接不畅，刷新一下或者换个网络试试？

________________________________
发件人: HAIYAA ***@***.***>
发送时间: Thursday, July 8, 2021 2:55:55 PM
收件人: Archie-King/caj2pdf-bookmark ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [Archie-King/caj2pdf-bookmark] readme图片失效了，不太清楚怎么操作，可以麻烦再补充一下么？ (#2)


Closed #2<https://github.com/Archie-King/caj2pdf-bookmark/issues/2>.

―
